default: 

	gcc main.c -o ./bin/srtp-2.0.0  -I../../../libs/srtp-2.0.0/include/  -I../../../libs/openssl/include -L../../../libs/srtp-2.0.0/lib  -L../../../libs/openssl/lib -lcrypto -lsrtp2 -g
	gcc main.c -o ./bin/srtp-2.1.0  -I../../../libs/srtp-2.1.0/include/  -I../../../libs/openssl/include -L../../../libs/srtp-2.1.0/lib  -L../../../libs/openssl/lib -lcrypto -lsrtp2 -g
	gcc main.c -o ./bin/srtp-2.2.0  -I../../../libs/srtp-2.2.0/include/  -I../../../libs/openssl/include -L../../../libs/srtp-2.2.0/lib  -L../../../libs/openssl/lib -lcrypto -lsrtp2 -g
	gcc main.c -o ./bin/srtp-master -I../../../libs/srtp-master/include/ -I../../../libs/openssl/include -L../../../libs/srtp-master/lib -L../../../libs/openssl/lib -lcrypto -lsrtp2 -g